### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by serl** [PhotonDesigner/instant-messenger#1]
Hello Tom,
Thanks for the great content!

I have a little question on this part of the code:

https://github.com/PhotonDesigner/instant-messenger/blob/ad41f3581cdae610ce041b753847d1dc67909e99/sim/views.py#L58-L61

Wouldn't this hammer the database with continuous requests, multiplied by the number of users connected? 🤔 

Thanks a lot, have a nice day!

**Comment by a-toms** [comment]
Hi @serl 👋 You're welcome and well done for finding me here :)

Thanks for the question. The answer is yes - it would hammer the database. 

In practice, with more than a few users you'd want to add at least some delay. I added this as the simplest way to get an instant messenger, without any concern for performance.

Here's a rough sketch of the change you might make (roughly written - I haven't run this):
```python
       # Continuously check for new messages
        while True:
            new_messages = models.Message.objects.filter(id__gt=last_id).order_by('created_at').values(
                'id', 'author__name', 'content'
            )
            async for message in new_messages:
                yield f"data: {json.dumps(message)}\n\n"
                last_id = message['id']
            await asyncio.sleep(1)  # Adjust sleep time as needed
```

Let me know if you have any other questions serl 👍
